# Generated by Django 5.2 on 2025-04-16 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.ImageField(upload_to='uploads/original/3672b3ac-ef33-4dd2-add5-63e9b7642e51.jpg')),
                ('yolo_processed_file', models.ImageField(blank=True, null=True, upload_to='uploads/yolo/dfe089cc-2f76-4797-a2ea-511861178996.jpg')),
                ('hog_processed_file', models.ImageField(blank=True, null=True, upload_to='uploads/hog/11a50750-f1fc-48d2-b729-b2a5d484075a.jpg')),
                ('yolo_counter', models.IntegerField(blank=True, null=True)),
                ('hog_counter', models.IntegerField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
